import type { Artist } from '../src/types'

function makeArtist(partial: Partial<Artist> & Pick<Artist, 'id' | 'nameHe'>): Artist {
  return {
    nameEn: undefined,
    aliases: [],
    secondaryGenres: [],
    region: 'center',
    answerEligible: true,
    ids: {},
    ...partial,
  }
}

// 12 fake artists covering every tile branch used by the unit tests.
export const fixtures: Artist[] = [
  makeArtist({
    id: 'pop-alpha',
    nameHe: 'אמן פופ א',
    nameEn: 'Pop Alpha',
    aliases: ['אלפא'],
    debutYear: 2010,
    breakthroughYear: 2012,
    type: 'solo',
    members: 1,
    gender: 'male',
    primaryGenre: 'pop',
    popularityTier: 5,
    region: 'tel-aviv-area',
  }),
  makeArtist({
    id: 'pop-beta',
    nameHe: 'אמן פופ ב',
    nameEn: 'Pop Beta',
    aliases: ['ביטא'],
    debutYear: 2011,
    breakthroughYear: 2013,
    type: 'solo',
    members: 1,
    gender: 'female',
    primaryGenre: 'pop',
    popularityTier: 4,
    region: 'tel-aviv-area',
  }),
  makeArtist({
    id: 'mizrahi-1',
    nameHe: 'זמר מזרחי',
    nameEn: 'Mizrahi Singer',
    aliases: [],
    debutYear: 1998,
    breakthroughYear: 2001,
    type: 'solo',
    members: 1,
    gender: 'male',
    primaryGenre: 'mizrahi',
    secondaryGenres: ['pop'],
    popularityTier: 3,
    region: 'south',
  }),
  makeArtist({
    id: 'rock-band',
    nameHe: 'להקת רוק א',
    nameEn: 'Rock Band A',
    aliases: [],
    debutYear: 1985,
    breakthroughYear: 1987,
    type: 'band',
    members: 4,
    gender: 'mixed',
    primaryGenre: 'rock',
    popularityTier: 2,
    region: 'center',
  }),
  makeArtist({
    id: 'rock-band2',
    nameHe: 'להקת רוק ב',
    nameEn: 'Rock Band B',
    aliases: [],
    debutYear: 1990,
    breakthroughYear: 1993,
    type: 'band',
    members: 3,
    gender: 'male',
    primaryGenre: 'rock',
    secondaryGenres: ['indie-alt', 'pop'],
    popularityTier: 3,
    region: 'center',
  }),
  makeArtist({
    id: 'rock-duo',
    nameHe: 'צמד רוק',
    nameEn: 'Rock Duo',
    aliases: [],
    debutYear: 1995,
    breakthroughYear: 1997,
    type: 'duo',
    members: 2,
    gender: 'male',
    primaryGenre: 'rock',
    popularityTier: 1,
    region: 'jerusalem',
  }),
  makeArtist({
    id: 'hiphop-m',
    nameHe: 'ראפר',
    nameEn: 'Rapper',
    aliases: ['ראפ'],
    debutYear: 2015,
    breakthroughYear: 2018,
    type: 'solo',
    members: 1,
    gender: 'male',
    primaryGenre: 'hiphop',
    secondaryGenres: ['mediterranean'],
    popularityTier: 4,
    region: 'tel-aviv-area',
  }),
  makeArtist({
    id: 'electro-duo',
    nameHe: 'צמד אלקטרוני',
    nameEn: 'Electro Duo',
    aliases: [],
    debutYear: 2008,
    breakthroughYear: 2010,
    type: 'duo',
    members: 2,
    gender: 'mixed',
    primaryGenre: 'electronic',
    secondaryGenres: ['indie-alt'],
    popularityTier: 3,
    region: 'haifa-north',
  }),
  makeArtist({
    id: 'folk-1',
    nameHe: 'זמר שירי ארץ ישראל',
    nameEn: 'Folk Singer',
    aliases: [],
    debutYear: 1970,
    breakthroughYear: 1973,
    type: 'solo',
    members: 1,
    gender: 'male',
    primaryGenre: 'folk-israeli',
    popularityTier: 2,
    region: 'south',
  }),
  makeArtist({
    id: 'soul-1',
    nameHe: 'זמרת סול',
    nameEn: 'Soul Singer',
    aliases: [],
    debutYear: 2013,
    breakthroughYear: 2016,
    type: 'solo',
    members: 1,
    gender: 'female',
    primaryGenre: 'jazz-soul',
    secondaryGenres: ['pop'],
    popularityTier: 4,
    region: 'abroad',
  }),
  makeArtist({
    id: 'indie-1',
    nameHe: 'הרכב אינדי',
    nameEn: 'Indie Act',
    aliases: [],
    debutYear: 2005,
    breakthroughYear: 2007,
    type: 'band',
    members: 5,
    gender: 'mixed',
    primaryGenre: 'indie-alt',
    popularityTier: 1,
    region: 'tel-aviv-area',
  }),
  makeArtist({
    id: 'religious-1',
    nameHe: 'זמר חסידי',
    nameEn: 'Religious Pop',
    aliases: [],
    debutYear: 2012,
    breakthroughYear: 2014,
    type: 'solo',
    members: 1,
    gender: 'male',
    primaryGenre: 'religious-pop',
    popularityTier: 3,
    region: 'jerusalem',
  }),
]

export const fixturesById: Map<string, Artist> = new Map(
  fixtures.map((a) => [a.id, a]),
)