// 09-curation-sheet.ts - the owner-facing worklist.
//
// The pipeline can only automate so much. Two gaps need a human with real
// sources, and both are player-visible:
//
//   1. debutYear is 0 (the "unknown" sentinel) for artists that no stage could
//      date. That makes them ineligible as daily answers and renders their
//      debut tile as "-".
//   2. members is 0 for bands whose size nobody recorded, so the lineup tile
//      shows a bare "להקה" with no count.
//
// Automated backfill was tried and rejected (see DECISIONS.md): name-based
// Deezer lookup matched the wrong artist in 25 of 33 cases, and MusicBrainz by
// MBID resolved only 8 of 65 and invented a posthumous release for one dead
// artist. So this stage does not guess. It emits a worksheet with everything
// needed to look each artist up, and it stays in sync with the data because it
// regenerates from artists.json.
import { readJson, writeFileSync, log } from './common.ts'
import type { Artist } from '../src/types'

interface Row {
  artist: Artist
  fields: string[]
}

function sheet(artists: Artist[]): string {
  const missingDebut = artists.filter((a) => !a.debutYear)
  const bandsNoCount = artists.filter((a) => a.type === 'band' && a.members === 0)

  const line = (r: Row): string => {
    const a = r.artist
    const name = a.nameEn ? `${a.nameHe} / ${a.nameEn}` : a.nameHe
    const cells = [
      `\`${a.id}\``,
      name,
      a.birthYear ? String(a.birthYear) : '?',
      a.diedYear ? String(a.diedYear) : '',
      a.ids.wikidata ? `\`${a.ids.wikidata}\`` : '-',
      a.ids.musicbrainz ? `\`${a.ids.musicbrainz.slice(0, 8)}\`` : '-',
      `#${a.popularityRank}`,
      r.fields.join(' + '),
      '', // <- the owner fills this in
    ]
    return `| ${cells.join(' | ')} |`
  }

  const head = [
    '| id | name | birth | died | wikidata | mbid | pop | needs | value |',
    '|---|---|---|---|---|---|---|---|---|',
  ].join('\n')

  const out: string[] = []
  out.push('# Curation worksheet')
  out.push('')
  out.push('Generated by `scripts/09-curation-sheet.ts` from `public/data/artists.json`.')
  out.push('Do not edit this file; edit `data/overrides.json` and re-run the pipeline.')
  out.push('')
  out.push('Each row needs a value looked up from a real source, then added to')
  out.push('`data/overrides.json` keyed by the Hebrew name, e.g.')
  out.push('')
  out.push('```json')
  out.push('"יפה ירקוני": { "debutYear": 1947 }')
  out.push('"הסיקסטיז": { "members": 5 }')
  out.push('```')
  out.push('')
  out.push('## 1. Missing debut year')
  out.push('')
  out.push(
    `${missingDebut.length} artists. Each one is \`answerEligible: false\` (the eligibility`,
  )
  out.push('gate requires a debut year) so none can be a daily answer, and all are still guessable.')
  out.push('')
  out.push('Sources that were already tried and came back empty: Wikidata date claims,')
  out.push('MusicBrainz release dates, Deezer earliest album. Wikidata `activeSince` exists for')
  out.push('9 of them but is unreliable (Max Brod reads 1906, which is his birth year).')
  out.push('')
  out.push(head)
  for (const a of missingDebut) {
    const needs = ['debutYear']
    out.push(line({ artist: a, fields: needs }))
  }
  out.push('')
  out.push('## 2. Bands with no member count')
  out.push('')
  out.push(
    `${bandsNoCount.length} bands. The lineup tile shows a bare "להקה" for these; the count is`,
  )
  out.push('what makes a band guess distinguishable from a solo act, so it is worth filling in.')
  out.push('')
  out.push(head)
  for (const a of bandsNoCount) {
    out.push(line({ artist: a, fields: ['members'] }))
  }
  out.push('')
  return out.join('\n')
}

export function run(): { missingDebut: number; bandsNoCount: number } {
  const artists = readJson<Artist[]>('public/data/artists.json')
  const missingDebut = artists.filter((a) => !a.debutYear).length
  const bandsNoCount = artists.filter((a) => a.type === 'band' && a.members === 0).length
  writeFileSync('data/curation-worksheet.md', sheet(artists), 'utf8')
  log(`09: worksheet written (${missingDebut} missing debut, ${bandsNoCount} bands without a count)`)
  return { missingDebut, bandsNoCount }
}

if (process.argv[1]?.endsWith('09-curation-sheet.ts')) {
  run()
}