// All player-visible strings, centralised in Hebrew. The app renders RTL and
// reads from this single module so another language can be added later.
// NOTE: Hebrew geresh/apostrophe uses U+05F3 (׳), never ASCII '.

export const strings = {
  title: 'אמנדל',
  subtitle: 'נחשו את האמן הישראלי היומי',
  guessCounter: 'ניחוש {n} מתוך {max}',
  placeholder: 'הקלידו שם של אמן או להקה...',
  submit: 'נחשו',
  alreadyGuessed: 'כבר ניחשתם את האמן הזה',
  notFound: 'לא מצאנו אמן בשם הזה',
  win: 'כל הכבוד! זה {name}',
  lose: 'לא הפעם. האמן היה {name}',
  winShort: 'ניצחתם!',
  loseShort: 'הפסדתם',
  share: 'שתפו',
  copied: 'הועתק ללוח!',
  nextIn: 'המשחק הבא בעוד {time}',
  guessesUsed: '{n}/10',
  numberOfDay: 'משחק מספר {n}',
  statsTitle: 'סטטיסטיקה',
  close: 'סגירה',
  newGameDisabled: 'המשחק נגמר להיום, חוזרים מחר!',
  legendCorrect: 'נכון',
  legendClose: 'קרוב',
  legendWrong: 'לא נכון',
  legendArrow: 'החץ מראה את הכיוון לערך האמיתי',
  arrowUp: 'הערך האמיתי גבוה יותר',
  arrowDown: 'הערך האמיתי נמוך יותר',
  columns: {
    debutYear: 'גיל',
    breakthrough: 'שנת פריצה',
    lineup: 'הרכב',
    gender: 'מגדר',
    genre: 'ז׳אנר',
    popularity: 'פופולריות',
  } as const,
  lineupValues: {
    solo: 'סולו',
    duo: 'צמד',
    band: 'להקה ({n})',
  },
  genderValues: {
    male: 'גבר',
    female: 'אישה',
    mixed: 'מעורב',
  },
  genreValues: {
    pop: 'פופ',
    mizrahi: 'מזרחית',
    rock: 'רוק',
    hiphop: 'היפ-הופ',
    mediterranean: 'ים-תיכוני',
    electronic: 'אלקטרוני',
    'ethnic-world': 'אתנו/עולם',
    'folk-israeli': 'שיר עברי',
    'indie-alt': 'אינדי',
    'religious-pop': 'פופ דתי',
    'jazz-soul': 'ג׳אז/סול',
    other: 'אחר',
  },
  popularityText: 'עוצמת פופולריות {n}/5',
  stats: {
    played: 'שיחקתם',
    winRate: 'אחוז ניצחונות',
    streak: 'רצף נוכחי',
    maxStreak: 'רצף שיא',
    distribution: 'התפלגות ניחושים',
    guessCount: 'ניחוש {n}',
    noStats: 'אין עדיין סטטיסטיקה. השלימו את המשחק של היום!',
  },
  helpTitle: 'איך משחקים?',
  helpBody:
    'מדי יום נבחר אמן ישראלי אחד. נסו לנחש מי הוא מתוך 10 ניחושים. אחרי כל ניחוש נגלה לכם כמה רמזים בצורת צבעים: ירוק = נכון, צהוב = קרוב, שחור = לא נכון, וחצים שמראים את הכיוון לערך האמיתי. כל השחקנים מקבלים את אותו האמן באותו יום.',
  footerCredits: 'נתונים: Wikidata, MusicBrainz, Last.fm, Deezer',
  reportMistake: 'דיווחו על טעות בנתונים',
  loadingData: 'טוענים נתונים…',
  errorLoading: 'טעינת הנתונים נכשלה. בדקו את החיבור ונסו שוב',
  retry: 'נסו שוב',
  staleDataNote: 'מציגים נתונים שהורדו קודם, ייתכן שאינם מעודכנים',
  btnHelp: 'עזרה',
  btnStats: 'סטטיסטיקה',
  btnSettings: 'הגדרות',
  boardEmpty: 'נסו לנחש אמן או להקה. אחרי כל ניחוש תראו את צבעי הרמזים.',
  settingsTitle: 'הגדרות',
  themeLight: 'מצב בהיר',
  themeDark: 'מצב כהה',
  colorblind: 'מצב עיוורי צבעים',
  shareTitle: 'שתפו את התוצאה',
  pickFromList: 'בחרו מהרשימה או לחצו Enter',
  revealCardTitle: 'האמן של היום',
  revealPictureAlt: 'תמונה של {name}',
  revealHitLabel: 'הלהיט הגדול',
  revealListen: 'האזינו ב-SoundCloud',
  revealNoSound: 'השיר זמין ב-SoundCloud',
  revealSearch: 'חיפוש ב-SoundCloud',
  revealNoPicture: 'אין תמונה זמינה',
} as const

export type Strings = typeof strings